# Generated by Django 5.1.6 on 2025-03-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_paymentwaiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwaiting',
            name='phone_number',
            field=models.CharField(default='+254713934480', max_length=20),
        ),
    ]
