# Generated by Django 5.1.6 on 2025-03-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('item', models.IntegerField()),
                ('image_url', models.URLField()),
                ('status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=150)),
                ('username', models.CharField(max_length=150)),
            ],
        ),
    ]
