# Generated by Django 5.1.6 on 2025-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productId',
            field=models.IntegerField(default=0),
        ),
    ]
