# Generated by Django 5.1.6 on 2025-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_cartegorygroup_cartegory_cartegory_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartegorygroup',
            name='group_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
