# Generated by Django 5.1.6 on 2025-03-10 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_cartegorygroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cartegory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cartegory', to='products.cartegory', to_field='cartegory_name'),
        ),
    ]
