# Generated by Django 5.1.6 on 2025-03-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
