# Generated by Django 5.1.6 on 2025-03-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_new_alter_product_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
    ]
