# Generated by Django 5.1.6 on 2025-03-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='number_bought',
            field=models.IntegerField(default=0),
        ),
    ]
