# Generated by Django 5.1.6 on 2025-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_duration',
            field=models.IntegerField(default=0),
        ),
    ]
