# Generated by Django 5.1.6 on 2025-03-20 10:25

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_offer_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='the description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_details',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
